version: "3.2"

services:
  node:
    build:
      context: ./src/
      dockerfile: ./Dockerfile
    command: /wait-for-it.sh mongo:27017 -- npm start
    ports:
      - 3000:3000
    depends_on:
      - mongo
    networks:
      - default
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    networks:
      - default

networks:
  default:
